version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forumhub_app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: forumhub_redis
    ports:
      - "6379:6379"
