version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forumhub_app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    container_name: forumhub_redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: forumhub_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: forumhub_api
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
